use std::collections::HashMap;
use std::path::Path;

use schemars::JsonSchema;
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use super::error::{parse_error, ConfigError};
use super::template;

/// Pipeline configuration (`pipelines/*.yml`).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct PipelineConfig {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub inputs: Vec<PipelineInput>,
    pub steps: Vec<PipelineStep>,
    #[serde(default)]
    pub output: Option<PipelineOutput>,
    /// Per-pipeline approval channel override (ADR-0022 §"Resolution
    /// order"). When set, takes precedence over the project's
    /// `default_approval_channel:`. The value must match the `name:` of
    /// an entry under `project.yml::approvals:`.
    #[serde(default)]
    pub approval_channel: Option<String>,
    /// Exposure declarations (ADR-0033). Opt-in per pipeline — `None`
    /// means the pipeline is invisible to MCP clients.
    #[serde(default)]
    pub expose: Option<PipelineExpose>,
}

/// Container for per-pipeline exposure surfaces. Today only `mcp:`
/// matters (ADR-0033); future adapters (HTTP, websocket, etc.) slot in
/// as additional optional fields.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
pub struct PipelineExpose {
    #[serde(default)]
    pub mcp: Option<McpExpose>,
}

/// MCP exposure for a single pipeline (ADR-0033 §2).
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
pub struct McpExpose {
    /// Tool name surfaced via `tools/list`. Defaults to the pipeline
    /// name when omitted.
    #[serde(default)]
    pub name: Option<String>,
    /// Tool description surfaced via `tools/list`. Defaults to the
    /// pipeline's `description:` when omitted.
    #[serde(default)]
    pub description: Option<String>,
    /// Execution-mode hint. The tool descriptor is identical either way:
    /// whether a call runs sync (blocking `tools/call`) or async is decided
    /// by the *client* task-augmenting the request (SEP-1686). `async`
    /// signals that callers SHOULD task-augment because the pipeline runs
    /// long.
    #[serde(default)]
    pub mode: McpExposeMode,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum McpExposeMode {
    #[default]
    Sync,
    /// Hint that callers SHOULD task-augment `tools/call` (SEP-1686)
    /// because the pipeline runs long. Listed in `tools/list` like any
    /// sync pipeline since Slice 2a.
    Async,
}

/// A declared input parameter for the pipeline.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct PipelineInput {
    pub name: String,
    #[serde(default, rename = "type")]
    pub ty: PipelineInputType,
    #[serde(default)]
    pub required: bool,
    /// Human/agent-facing description, surfaced in MCP `tools/list`
    /// (ADR-0033). Optional but strongly recommended on pipelines that opt
    /// in to MCP exposure.
    #[serde(default)]
    pub description: Option<String>,
}

/// JSON Schema type tag for a [`PipelineInput`]. The set matches JSON
/// Schema draft 2020-12 primitive `type` values (minus `null`), so the
/// shape generated by [`PipelineConfig::inputs_json_schema`] is a valid
/// MCP tool input schema.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum PipelineInputType {
    #[default]
    String,
    Integer,
    Number,
    Boolean,
    Object,
    Array,
}

impl PipelineInputType {
    /// JSON Schema `type` value as a static string.
    pub fn as_schema_str(self) -> &'static str {
        match self {
            Self::String => "string",
            Self::Integer => "integer",
            Self::Number => "number",
            Self::Boolean => "boolean",
            Self::Object => "object",
            Self::Array => "array",
        }
    }
}

impl PipelineConfig {
    /// MCP exposure declaration if any — `expose.mcp` shortcut (ADR-0033).
    pub fn mcp_exposure(&self) -> Option<&McpExpose> {
        self.expose.as_ref().and_then(|e| e.mcp.as_ref())
    }

    /// Tool name surfaced to MCP clients (`expose.mcp.name` override,
    /// falling back to the pipeline name). `None` when the pipeline is
    /// not exposed.
    pub fn mcp_tool_name(&self) -> Option<&str> {
        self.mcp_exposure()
            .map(|m| m.name.as_deref().unwrap_or(self.name.as_str()))
    }

    /// Tool description surfaced to MCP clients (`expose.mcp.description`
    /// override, falling back to the pipeline description). `None` when
    /// either the pipeline is not exposed or both fields are unset.
    pub fn mcp_tool_description(&self) -> Option<&str> {
        let m = self.mcp_exposure()?;
        m.description
            .as_deref()
            .or(self.description.as_deref())
    }

    /// JSON Schema object describing this pipeline's `inputs:` block, in
    /// the shape expected by MCP `tools/list` for tool input schemas
    /// (ADR-0033 §3). Always returns `{ "type": "object", "properties":
    /// {...}, "required": [...], "additionalProperties": false }`, even
    /// when `inputs:` is empty — that yields a valid no-argument tool.
    pub fn inputs_json_schema(&self) -> serde_json::Value {
        use serde_json::{json, Map, Value};
        let mut properties = Map::new();
        let mut required = Vec::new();
        for input in &self.inputs {
            let mut prop = Map::new();
            prop.insert("type".into(), Value::String(input.ty.as_schema_str().into()));
            if let Some(desc) = &input.description {
                prop.insert("description".into(), Value::String(desc.clone()));
            }
            properties.insert(input.name.clone(), Value::Object(prop));
            if input.required {
                required.push(Value::String(input.name.clone()));
            }
        }
        json!({
            "type": "object",
            "properties": properties,
            "required": required,
            "additionalProperties": false,
        })
    }
}

/// A single step in the pipeline DAG.
///
/// A step is either an *agent* step (LLM ReAct loop, ADR pre-0024) or a
/// *deterministic tool* step (ADR-0024). Discriminated by which key is
/// present (`agent:` vs `tool:`); ambiguity / emptiness fail at parse time.
#[derive(Debug, Clone)]
pub struct PipelineStep {
    pub id: String,
    pub kind: PipelineStepKind,
    pub depends_on: Vec<String>,
    /// Optional runtime predicate (ADR-0028). When `Some`, the step runs only
    /// if the expression evaluates to true after dependencies complete.
    /// `${inputs.*}` / `${steps.*.output}` are substituted first; the parser
    /// then sees a fully-resolved string. Topology is unaffected.
    pub when: Option<String>,
    /// Optional per-step context policy (ADR-0031). Defaults to inherit
    /// (full sub-stream reconstruction, ADR-0016 §4 behaviour).
    pub context: Option<StepContextConfig>,
}

/// Per-step context construction policy (ADR-0031). The block is accepted
/// on every step shape but only takes effect on agent steps — tool steps
/// build no context.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
pub struct StepContextConfig {
    #[serde(default)]
    pub mode: StepContextMode,
}

/// Context construction modes for [`StepContextConfig`] (ADR-0031).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum StepContextMode {
    /// Default. ContextBuilder reads the full sub-stream — ADR-0016 §4
    /// behaviour, suited to conversational steps.
    #[default]
    Inherit,
    /// Layer C is filtered to events with `timestamp >= step_start`.
    /// Prior runs' events for the same `step_stream_id` are dropped.
    /// Suited to retrieval / analytical steps that should treat each run
    /// as an independent task.
    Fresh,
}

/// Step body. The two variants are mutually exclusive at the YAML level.
#[derive(Debug, Clone)]
pub enum PipelineStepKind {
    /// LLM ReAct step: the agent plans tool calls itself.
    Agent { agent: String, task: String },
    /// Deterministic tool step (ADR-0024): orchestrator dispatches the
    /// named tool with templated args, no LLM hop.
    Tool {
        tool: String,
        args: serde_yml::Value,
    },
}

impl PipelineStep {
    /// Convenience for legacy callers / tests that only care about agent
    /// steps. `None` for tool steps.
    pub fn agent_name(&self) -> Option<&str> {
        match &self.kind {
            PipelineStepKind::Agent { agent, .. } => Some(agent.as_str()),
            PipelineStepKind::Tool { .. } => None,
        }
    }
}

/// Wire format. Both arms' fields are optional so we can detect ambiguous
/// (`agent:` + `tool:`) and empty configs ourselves with a clear error
/// message instead of relying on serde's "did not match any variant" output.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
struct PipelineStepRaw {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub task: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schemars(with = "Option<serde_json::Value>")]
    pub args: Option<serde_yml::Value>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub depends_on: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub when: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<StepContextConfig>,
}

impl<'de> Deserialize<'de> for PipelineStep {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::Error;
        let raw = PipelineStepRaw::deserialize(d)?;
        let has_agent = raw.agent.is_some() || raw.task.is_some();
        let has_tool = raw.tool.is_some() || raw.args.is_some();
        let kind = match (has_agent, has_tool) {
            (true, true) => {
                return Err(D::Error::custom(format!(
                    "step `{}`: cannot specify both `agent:` and `tool:` (ADR-0024)",
                    raw.id
                )));
            }
            (false, false) => {
                return Err(D::Error::custom(format!(
                    "step `{}`: must specify either `agent:` + `task:` or `tool:` (ADR-0024)",
                    raw.id
                )));
            }
            (true, false) => {
                let agent = raw.agent.ok_or_else(|| {
                    D::Error::custom(format!("step `{}`: `agent:` is required", raw.id))
                })?;
                let task = raw.task.ok_or_else(|| {
                    D::Error::custom(format!(
                        "step `{}`: `task:` is required for agent steps",
                        raw.id
                    ))
                })?;
                PipelineStepKind::Agent { agent, task }
            }
            (false, true) => {
                let tool = raw.tool.ok_or_else(|| {
                    D::Error::custom(format!(
                        "step `{}`: `tool:` is required for tool steps",
                        raw.id
                    ))
                })?;
                let args = raw.args.unwrap_or(serde_yml::Value::Null);
                PipelineStepKind::Tool { tool, args }
            }
        };
        Ok(PipelineStep {
            id: raw.id,
            kind,
            depends_on: raw.depends_on,
            when: raw.when,
            context: raw.context,
        })
    }
}

impl Serialize for PipelineStep {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        let raw = match &self.kind {
            PipelineStepKind::Agent { agent, task } => PipelineStepRaw {
                id: self.id.clone(),
                agent: Some(agent.clone()),
                task: Some(task.clone()),
                tool: None,
                args: None,
                depends_on: self.depends_on.clone(),
                when: self.when.clone(),
                context: self.context.clone(),
            },
            PipelineStepKind::Tool { tool, args } => PipelineStepRaw {
                id: self.id.clone(),
                agent: None,
                task: None,
                tool: Some(tool.clone()),
                args: Some(args.clone()),
                depends_on: self.depends_on.clone(),
                when: self.when.clone(),
                context: self.context.clone(),
            },
        };
        raw.serialize(s)
    }
}

impl JsonSchema for PipelineStep {
    fn schema_name() -> String {
        "PipelineStep".into()
    }
    fn json_schema(gen: &mut schemars::gen::SchemaGenerator) -> schemars::schema::Schema {
        // The user-visible YAML is fully described by the Raw struct; we
        // accept that the schema does not encode the agent/tool oneOf
        // constraint (ADR-0024 "tech implications": JsonSchema isn't a
        // stable artefact yet).
        PipelineStepRaw::json_schema(gen)
    }
}

/// Declares which step produces the final pipeline output.
///
/// Two shapes (ADR-0029):
///
/// - `{ step: <id> }` — single terminal step. Hard-fails if that step was
///   skipped (ADR-0028 §"Skip semantics").
/// - `{ any_of: [<id>, ...] }` — routed output: walk the list in order and
///   take the first id that was not skipped. Hard-fails if every id was
///   skipped. Designed for concierge / triage pipelines where `when:` on
///   branches already encodes mutual exclusivity.
#[derive(Debug, Clone, Serialize, JsonSchema)]
#[serde(untagged)]
pub enum PipelineOutput {
    Step(StepOutput),
    AnyOf(AnyOfOutput),
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct StepOutput {
    pub step: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct AnyOfOutput {
    pub any_of: Vec<String>,
}

impl PipelineOutput {
    /// Convenience for callers that only care about the legacy single-step
    /// shape (e.g. DAG plan placement). Returns `None` for `any_of:`.
    pub fn single_step(&self) -> Option<&str> {
        match self {
            PipelineOutput::Step(s) => Some(s.step.as_str()),
            PipelineOutput::AnyOf(_) => None,
        }
    }

    /// All step ids this output declaration can resolve to, in declared
    /// order. Used by validation and tests.
    pub fn declared_steps(&self) -> Vec<&str> {
        match self {
            PipelineOutput::Step(s) => vec![s.step.as_str()],
            PipelineOutput::AnyOf(a) => a.any_of.iter().map(String::as_str).collect(),
        }
    }
}

/// Custom deserialise: `#[serde(untagged)]` produces unhelpful "data did not
/// match any variant" errors on typos. Inspect the YAML mapping ourselves and
/// route by the present key, with a pointed error otherwise.
impl<'de> Deserialize<'de> for PipelineOutput {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::Error;
        let value = serde_yml::Value::deserialize(d)?;
        let map = value
            .as_mapping()
            .ok_or_else(|| D::Error::custom("`output:` must be a mapping"))?;
        let has_step = map.contains_key(serde_yml::Value::String("step".into()));
        let has_any_of = map.contains_key(serde_yml::Value::String("any_of".into()));
        match (has_step, has_any_of) {
            (true, true) => Err(D::Error::custom(
                "`output:` cannot specify both `step:` and `any_of:` (ADR-0029)",
            )),
            (false, false) => {
                let keys: Vec<String> = map
                    .keys()
                    .filter_map(|k| k.as_str().map(String::from))
                    .collect();
                Err(D::Error::custom(format!(
                    "`output:` must specify either `step:` or `any_of:`; found keys: [{}]",
                    keys.join(", ")
                )))
            }
            (true, false) => StepOutput::deserialize(value)
                .map(PipelineOutput::Step)
                .map_err(D::Error::custom),
            (false, true) => AnyOfOutput::deserialize(value)
                .map(PipelineOutput::AnyOf)
                .map_err(D::Error::custom),
        }
    }
}

/// Load and parse a single pipeline YAML file.
///
/// `${inputs.*}` variables are left unresolved — they are filled at runtime.
pub fn load_pipeline(
    path: &Path,
    vars: &HashMap<String, String>,
) -> Result<PipelineConfig, ConfigError> {
    let raw = std::fs::read_to_string(path).map_err(|e| ConfigError::Io {
        path: path.to_path_buf(),
        source: e,
    })?;

    let resolved = template::resolve_templates(&raw, vars, path)?;

    let config: PipelineConfig =
        serde_yml::from_str(&resolved).map_err(|e| parse_error(path, &resolved, e))?;

    Ok(config)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::TempDir;

    fn write_file(dir: &TempDir, name: &str, content: &str) -> std::path::PathBuf {
        let path = dir.path().join(name);
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(content.as_bytes()).unwrap();
        path
    }

    #[test]
    fn minimal_pipeline() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: simple
steps:
  - id: step1
    agent: helper
    task: "do something"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(config.name, "simple");
        assert_eq!(config.steps.len(), 1);
        assert!(config.steps[0].depends_on.is_empty());
        assert_eq!(config.steps[0].agent_name(), Some("helper"));
    }

    #[test]
    fn tool_step_parses() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: ingest
steps:
  - id: fetch
    tool: git_pull
    args:
      repo: "https://example.com/r"
      ref: main
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        match &config.steps[0].kind {
            PipelineStepKind::Tool { tool, args } => {
                assert_eq!(tool, "git_pull");
                assert!(args.get("repo").is_some());
            }
            _ => panic!("expected tool step"),
        }
    }

    #[test]
    fn tool_step_without_args_defaults_to_null() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: p
steps:
  - id: s
    tool: noop
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        match &config.steps[0].kind {
            PipelineStepKind::Tool { args, .. } => {
                assert!(args.is_null());
            }
            _ => panic!(),
        }
    }

    #[test]
    fn step_with_both_agent_and_tool_rejected() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: bad
steps:
  - id: s
    agent: a
    task: t
    tool: x
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let err = load_pipeline(&path, &HashMap::new()).unwrap_err();
        assert!(matches!(err, ConfigError::Parse { detail, .. } if detail.contains("both")));
    }

    #[test]
    fn step_with_neither_agent_nor_tool_rejected() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: bad
steps:
  - id: s
    depends_on: []
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let err = load_pipeline(&path, &HashMap::new()).unwrap_err();
        assert!(matches!(err, ConfigError::Parse { detail, .. } if detail.contains("either")));
    }

    #[test]
    fn agent_step_without_task_rejected() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: bad
steps:
  - id: s
    agent: a
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let err = load_pipeline(&path, &HashMap::new()).unwrap_err();
        assert!(matches!(err, ConfigError::Parse { detail, .. } if detail.contains("task")));
    }

    #[test]
    fn pipeline_with_dag() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: research
inputs:
  - name: query
    required: true
steps:
  - id: search
    agent: researcher
    task: "Search for: ${inputs.query}"
  - id: analyze
    agent: researcher
    task: "Analyze results"
    depends_on: [search]
  - id: summarize
    agent: researcher
    task: "Summarize"
    depends_on: [analyze]
  - id: review
    agent: researcher
    task: "Review"
    depends_on: [analyze]
output:
  step: summarize
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(config.steps.len(), 4);
        assert_eq!(config.steps[1].depends_on, vec!["search"]);
        assert_eq!(config.steps[2].depends_on, vec!["analyze"]);
        assert_eq!(config.steps[3].depends_on, vec!["analyze"]);
        assert_eq!(
            config.output.unwrap().single_step(),
            Some("summarize")
        );
    }

    #[test]
    fn pipeline_inputs_left_unresolved() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: test
steps:
  - id: s1
    agent: a
    task: "Query: ${inputs.q}"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        match &config.steps[0].kind {
            PipelineStepKind::Agent { task, .. } => assert!(task.contains("${inputs.q}")),
            _ => panic!(),
        }
    }

    #[test]
    fn pipeline_approval_channel_parses() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: deploy
approval_channel: ops_slack
steps:
  - id: ship
    agent: deployer
    task: "release"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(config.approval_channel.as_deref(), Some("ops_slack"));
    }

    #[test]
    fn pipeline_without_approval_channel_is_none() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: noop
steps:
  - id: s
    agent: a
    task: t
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert!(config.approval_channel.is_none());
    }

    #[test]
    fn pipeline_step_with_when_parses() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: concierge
steps:
  - id: router
    agent: concierge
    task: "decide"
  - id: short
    agent: helper
    task: "answer"
    depends_on: [router]
    when: "${steps.router.output} == 'short'"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert!(config.steps[0].when.is_none());
        assert_eq!(
            config.steps[1].when.as_deref(),
            Some("${steps.router.output} == 'short'")
        );
    }

    #[test]
    fn step_context_mode_fresh_parses() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: test
steps:
  - id: retrieve
    agent: researcher
    task: "find"
    context:
      mode: fresh
  - id: smalltalk
    agent: chat
    task: "hi"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(
            config.steps[0].context.as_ref().map(|c| c.mode),
            Some(StepContextMode::Fresh)
        );
        assert!(config.steps[1].context.is_none());
    }

    #[test]
    fn step_context_mode_inherit_is_default_when_unspecified() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: test
steps:
  - id: chat
    agent: a
    task: "hi"
    context: {}
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(
            config.steps[0].context.as_ref().map(|c| c.mode),
            Some(StepContextMode::Inherit)
        );
    }

    #[test]
    fn pipeline_default_input_type() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: test
inputs:
  - name: query
steps:
  - id: s1
    agent: a
    task: "go"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(config.inputs[0].ty, PipelineInputType::String);
        assert!(!config.inputs[0].required);
        assert!(config.inputs[0].description.is_none());
    }

    #[test]
    fn pipeline_input_parses_type_enum_and_description() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: test
inputs:
  - name: count
    type: integer
    required: true
    description: how many items to fetch
steps:
  - id: s1
    agent: a
    task: "go"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(config.inputs[0].ty, PipelineInputType::Integer);
        assert!(config.inputs[0].required);
        assert_eq!(
            config.inputs[0].description.as_deref(),
            Some("how many items to fetch")
        );
    }

    #[test]
    fn pipeline_input_rejects_unknown_type() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: test
inputs:
  - name: count
    type: int
steps:
  - id: s1
    agent: a
    task: "go"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let result = load_pipeline(&path, &HashMap::new());
        assert!(
            result.is_err(),
            "expected `type: int` (not in {{string,integer,number,boolean,object,array}}) to fail"
        );
    }

    #[test]
    fn inputs_json_schema_shape() {
        let config = PipelineConfig {
            name: "p".into(),
            description: None,
            inputs: vec![
                PipelineInput {
                    name: "query".into(),
                    ty: PipelineInputType::String,
                    required: true,
                    description: Some("search query".into()),
                },
                PipelineInput {
                    name: "limit".into(),
                    ty: PipelineInputType::Integer,
                    required: false,
                    description: None,
                },
            ],
            steps: vec![],
            output: None,
            approval_channel: None,
            expose: None,
        };
        let schema = config.inputs_json_schema();
        assert_eq!(schema["type"], "object");
        assert_eq!(schema["additionalProperties"], false);
        assert_eq!(schema["properties"]["query"]["type"], "string");
        assert_eq!(schema["properties"]["query"]["description"], "search query");
        assert_eq!(schema["properties"]["limit"]["type"], "integer");
        assert!(schema["properties"]["limit"].get("description").is_none());
        assert_eq!(
            schema["required"].as_array().unwrap(),
            &vec![serde_json::Value::String("query".into())]
        );
    }

    #[test]
    fn pipeline_without_expose_block_is_not_mcp_exposed() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: hidden
steps:
  - id: s1
    agent: a
    task: "go"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert!(config.expose.is_none());
        assert!(config.mcp_exposure().is_none());
        assert!(config.mcp_tool_name().is_none());
    }

    #[test]
    fn pipeline_with_expose_mcp_defaults_to_sync() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: search
description: pipeline-level desc
expose:
  mcp: {}
steps:
  - id: s1
    agent: a
    task: "go"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        let m = config.mcp_exposure().expect("expose.mcp present");
        assert_eq!(m.mode, McpExposeMode::Sync);
        assert!(m.name.is_none());
        assert_eq!(config.mcp_tool_name(), Some("search"));
        assert_eq!(config.mcp_tool_description(), Some("pipeline-level desc"));
    }

    #[test]
    fn pipeline_expose_mcp_overrides_name_and_description() {
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: search_internal
description: internal name + desc
expose:
  mcp:
    name: web_search
    description: search the public web
    mode: sync
steps:
  - id: s1
    agent: a
    task: "go"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(config.mcp_tool_name(), Some("web_search"));
        assert_eq!(config.mcp_tool_description(), Some("search the public web"));
    }

    #[test]
    fn pipeline_expose_mcp_async_parses() {
        // Slice 2 will switch the server on; for now we just need YAML to
        // parse so authors can declare async ahead of the feature flip.
        let dir = TempDir::new().unwrap();
        let yaml = r#"
name: long_job
expose:
  mcp:
    mode: async
steps:
  - id: s1
    agent: a
    task: "go"
"#;
        let path = write_file(&dir, "pipeline.yml", yaml);
        let config = load_pipeline(&path, &HashMap::new()).unwrap();
        assert_eq!(
            config.mcp_exposure().unwrap().mode,
            McpExposeMode::Async
        );
    }

    #[test]
    fn inputs_json_schema_empty_inputs() {
        let config = PipelineConfig {
            name: "p".into(),
            description: None,
            inputs: vec![],
            steps: vec![],
            output: None,
            approval_channel: None,
            expose: None,
        };
        let schema = config.inputs_json_schema();
        assert_eq!(schema["type"], "object");
        assert_eq!(schema["properties"], serde_json::json!({}));
        assert_eq!(schema["required"], serde_json::json!([]));
    }
}
